apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbm-slis-deployment
  labels:
    app: lbm-slis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lbm-slis
  template:
    metadata:
      labels:
        app: lbm-slis
    spec:
      containers:
      - name: lbm-slis-server
        image: gcr.io/next-2020-ops102/log-based-metrics-slis:latest
        ports:
        - containerPort: 8080