apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-11-29T01:30:55Z
  generation: 1
  labels:
    run: prometheus-demo-node
  name: prometheus-demo-node
  namespace: default
  resourceVersion: "1220091"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/prometheus-demo-node
  uid: 6adb9339-f376-11e8-8bdb-42010a8a0039
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: prometheus-demo-node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"      # must be quoted
        prometheus.io/port: "8080" # must be quoted
        prometheus.io/path: "/metrics"      # it defaults to /metrics
      creationTimestamp: null
      labels:
        run: prometheus-demo-node
    spec:
      containers:
      - image: docker.io/yurigrinshteyn/prometheus-demo-node:latest
        imagePullPolicy: Always
        name: prometheus-demo-node
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30